import json

with open('fixes/transitive-vulns.json') as f:
    vulns = json.load(f)

pr_body = "# 🔒 Fix Transitive Dependency Vulnerabilities\n\n"
pr_body += "This PR fixes vulnerabilities in **transitive dependencies** (dependencies of dependencies).\n\n"
pr_body += "## 🎯 Problem\n\n"
pr_body += "These vulnerabilities exist in dependencies that are brought in by your direct dependencies. "
pr_body += "They don't appear directly in your pom.xml/build.sbt files, but Maven/SBT pulls them in automatically.\n\n"
pr_body += "## ✅ Solution\n\n"
pr_body += "This PR uses **dependency management** to force secure versions:\n\n"
pr_body += "### For Maven (pom.xml):\n"
pr_body += "Added/updated `<dependencyManagement>` section to force secure versions of transitive dependencies.\n\n"
pr_body += "### For SBT (build.sbt):\n"
pr_body += "Added `dependencyOverrides` to force secure versions.\n\n"
pr_body += "## 🔴 Vulnerabilities Fixed\n\n"
pr_body += f"**Total:** {len(vulns)} vulnerable transitive dependencies\n\n"

critical = [v for v in vulns if v['severity'] == 'CRITICAL']
high = [v for v in vulns if v['severity'] == 'HIGH']

if critical:
    pr_body += "### 🔴 CRITICAL\n\n"
    for vuln in critical:
        pr_body += f"**{vuln['groupId']}:{vuln['artifactId']}**\n"
        pr_body += f"- Current: `{vuln['currentVersion']}`\n"
        pr_body += f"- Fixed: `{vuln['fixedVersion']}`\n"
        pr_body += f"- CVE: {vuln['cve']}\n\n"

if high:
    pr_body += "### 🟠 HIGH\n\n"
    for vuln in high:
        pr_body += f"**{vuln['groupId']}:{vuln['artifactId']}**\n"
        pr_body += f"- Current: `{vuln['currentVersion']}`\n"
        pr_body += f"- Fixed: `{vuln['fixedVersion']}`\n"
        pr_body += f"- CVE: {vuln['cve']}\n\n"

pr_body += "## 🧪 Testing\n\n"
pr_body += "Please verify:\n"
pr_body += "1. ✅ `mvn clean install` or `sbt compile` succeeds\n"
pr_body += "2. ✅ All tests pass\n"
pr_body += "3. ✅ Application runs correctly\n"
pr_body += "4. ✅ Check that transitive dependencies are overridden:\n"
pr_body += "   - Maven: `mvn dependency:tree`\n"
pr_body += "   - SBT: `sbt dependencyTree`\n\n"
pr_body += "## 📚 How This Works\n\n"
pr_body += "**Dependency Management** tells Maven/SBT:\n"
pr_body += '> "When ANY dependency requests package X, use version Y instead of what they ask for."\n\n'
pr_body += "This overrides vulnerable transitive dependency versions throughout your entire dependency tree.\n\n"
pr_body += "## ⚠️ Important\n\n"
pr_body += "- These changes affect your **entire dependency tree**\n"
pr_body += "- Test thoroughly to ensure no compatibility issues\n"
pr_body += "- Consider updating direct dependencies to versions that don't pull in vulnerable transitives\n\n"
pr_body += "---\n\n"
pr_body += "*Generated by: Fix Transitive Dependencies workflow*\n"

with open('fixes/pr-body.md', 'w') as f:
    f.write(pr_body)

print("✅ PR documentation generated")
